language: php

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.1

script:
  - if [[ ! -e mkdocs.yml ]]; then echo "Missing mkdocs.yml!" && return 1; fi
  - if [[ ! -d docs/book ]]; then echo "Missing docs/book/ sub-directory" && return 1; fi
