sudo: false

language: php

branches:
    only:
        - master

matrix:
    include:
        - php: 7.1

script:
  - if [[ ! -e mkdocs.yml ]]; then echo "Missing mkdocs.yml!" && return 1; fi
  - if [[ ! -d doc/book ]]; then echo "Missing doc/book/ sub-directory" && return 1; fi
